### ISSUE TITLE
Cannot `recap_and_rescale` tree sequence produced by saved SLiM script, because DFE metadata is missing

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1388]
The "Outputting a SLiM script" section of the tutorial (a few subsections down from [here](https://popsim-consortium.github.io/stdpopsim-docs/latest/tutorial.html#an-example-simulation)) gives an example of saving a SLiM script, then loading it back into python and recapitating via `Engine.recap_and_rescale`.

But, this doesn't work:
```
ts = tskit.load("foo.trees")
ts = engine.recap_and_rescale(ts, demography, contig, samples, slim_scaling_factor=10)                                                                                          
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/natep/projects/stdpopsim/stdpopsim/stdpopsim/slim_engine.py", line 1900, in recap_and_rescale
#     ts = self._recap_and_rescale(
#   File "/home/natep/projects/stdpopsim/stdpopsim/stdpopsim/slim_engine.py", line 1719, in _recap_and_rescale
#     for dfe in metadata["stdpopsim"]["DFEs"]:
# KeyError: 'stdpopsim'
```

The reason is because the DFE metadata is not created within the SLiM script -- it's retroactively added by `simulate` here:
https://github.com/popsim-consortium/stdpopsim/blob/e0900f1a41224b605faba6c9409966ac56b5c93f/stdpopsim/slim_engine.py#L1596

I think what we need to do here is add the same line to `Engine.recap_and_rescale` (not `Engine._recap_and_rescale` which is also used by `Engine.simulate`).

**Comment by nspope** [comment]
Should probably also add a test that:
- Saves a SLiM script
- Uses sed to alter output path for trees file to a non-temporary location
- Runs SLiM
- Loads in trees and recapitates
