### ISSUE TITLE
Change Python API so that species IDs are consistent with those in the CLI

### ISSUE THREAD

**Issue by gtsambos** [popsim-consortium/stdpopsim#349]
See this error I get in Python:
```
>>> species = stdpopsim.get_species("HomSap")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gtsambos/.local/lib/python3.7/site-packages/stdpopsim-0.1.dev221+g12926d3-py3.7.egg/stdpopsim/species.py", line 29, in get_species
ValueError: Species 'HomSap' not in catalog
>>> species = stdpopsim.get_species("homsap")
>>> 
```

**Comment by gtsambos** [comment]
Ah nvm, this was because of a conflict between the pip-installed and python development version. Sorry!
