### ISSUE TITLE
Incorrect version pinning for attrs

### ISSUE THREAD

**Issue by hyanwong** [popsim-consortium/stdpopsim#394]
On a fresh install on OS X 10.14, I can't seem to type `import stdpopsim` in a Python 3.7 console: see the error message at the end of the output below.

```
yan$ python3 -m pip install stdpopsim
Collecting stdpopsim
  Using cached https://files.pythonhosted.org/packages/74/d5/587b8df4b789e365e6dda11d84b72f232dc70b7f2bea087fc82874b11cc4/stdpopsim-0.1.1.tar.gz
Requirement already satisfied: msprime>=0.7.1 in /usr/local/lib/python3.7/site-packages (from stdpopsim) (0.7.4.dev26+gab92765)
Requirement already satisfied: attrs>=18.2.0 in /usr/local/lib/python3.7/site-packages (from stdpopsim) (18.2.0)
Requirement already satisfied: appdirs in /usr/local/lib/python3.7/site-packages (from stdpopsim) (1.4.3)
Requirement already satisfied: humanize in /usr/local/lib/python3.7/site-packages (from stdpopsim) (0.5.1)
Requirement already satisfied: tskit in /usr/local/lib/python3.7/site-packages (from msprime>=0.7.1->stdpopsim) (0.2.4.dev0)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.7/site-packages (from msprime>=0.7.1->stdpopsim) (1.17.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.7/site-packages (from tskit->msprime>=0.7.1->stdpopsim) (2.8.0)
Requirement already satisfied: svgwrite in /usr/local/lib/python3.7/site-packages (from tskit->msprime>=0.7.1->stdpopsim) (1.2.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/site-packages (from tskit->msprime>=0.7.1->stdpopsim) (2.6.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from h5py->tskit->msprime>=0.7.1->stdpopsim) (1.12.0)
Requirement already satisfied: pyparsing>=2.0.1 in /usr/local/lib/python3.7/site-packages (from svgwrite->tskit->msprime>=0.7.1->stdpopsim) (2.3.0)
Building wheels for collected packages: stdpopsim
  Building wheel for stdpopsim (setup.py) ... done
  Created wheel for stdpopsim: filename=stdpopsim-0.1.1-cp37-none-any.whl size=52792 sha256=44e740ca56b00f51dd694cf5dcd9f2948de2dbbd6b6836a7fe76d9ca680d27dd
  Stored in directory: /Users/yan/Library/Caches/pip/wheels/12/b2/05/995eb66ed306279346216a41fdc9ec7a68d885ed891caa449a
Successfully built stdpopsim
Installing collected packages: stdpopsim
Successfully installed stdpopsim-0.1.1

yan$ python3
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stdpopsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/stdpopsim/__init__.py", line 13, in <module>
    from . species import *  # NOQA
  File "/usr/local/lib/python3.7/site-packages/stdpopsim/species.py", line 10, in <module>
    from . import genomes
  File "/usr/local/lib/python3.7/site-packages/stdpopsim/genomes.py", line 13, in <module>
    class Genome(object):
  File "/usr/local/lib/python3.7/site-packages/attr/_make.py", line 904, in attrs
    return wrap(maybe_cls)
  File "/usr/local/lib/python3.7/site-packages/attr/_make.py", line 855, in wrap
    cache_hash,
  File "/usr/local/lib/python3.7/site-packages/attr/_make.py", line 471, in __init__
    cls, these, auto_attribs, kw_only
  File "/usr/local/lib/python3.7/site-packages/attr/_make.py", line 416, in _transform_attrs
    a=a
ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute.  Attribute in question: Attribute(name='length', default=0, validator=None, repr=True, cmp=True, hash=None, init=False, metadata=mappingproxy({}), type=None, converter=None, kw_only=False)

```

**Comment by jeromekelleher** [comment]
Odd. Can you run ``pip install --upgrade attrs`` and try again please? We might have gotten the version pinning wrong and 18.2.0 isn't new enough.

**Comment by hyanwong** [comment]
Yes, when I upgrade attrs to the latest (19.3) rather than 18.2.0 which I had installed, it works. I guess you want versions > 19?

**Comment by jeromekelleher** [comment]
Yes, it looks like we need >= 19.0. I've updated this as a bug.

**Comment by jeromekelleher** [comment]
It would be very helpful if someone could try out version 19.0 of attrs and check.

**Comment by jeromekelleher** [comment]
Reported upstream on the conda-forge package also, which will need to be fixed.

**Comment by hyanwong** [comment]
> It would be very helpful if someone could try out version 19.0 of attrs and check.

On my system, the only relevant versions listed by pip are `18.1.0, 18.2.0, 19.1.0, 19.2.0, 19.3.0`. I can confirm that the bug occurs with 18.2.0, but not with 19.1.0 upwards

**Comment by jeromekelleher** [comment]
Great, thanks. Let's pin  >=19.1.0 then.
