### ISSUE TITLE
SLiM engine can't do DroMel/OutOfAfrica_2L06

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#456]
With `--slim-scaling-factor 1000`, SLiM runs out of memory on my 16gb laptop. Probably the `simplificationRatio`/`simplificationInterval` needs some fine tuning; currently we use the SLiM defaults.
```
$ time stdpopsim -e slim -vv --slim-scaling-factor 1000 DroMel -d OutOfAfrica_2L06 -c chr4 50 50 -o /tmp/DroMel_OutOfAfrica_2L06.trees
2020-04-01 14:39:25,344 [317884] DEBUG stdpopsim.species: Making flat chromosome 1 * chr4
2020-04-01 14:39:25,344 [317884] INFO stdpopsim.cli: Running simulation model OutOfAfrica_2L06 for DroMel on Contig(length=1.3E+06, recombination_rate=8.4E-09, mutation_rate=5.5E-09, genetic_map=None) with 100 samples using slim.
Simulation information:
    Engine: slim (3.3.2)
    Model id: OutOfAfrica_2L06
    Model desciption: Three epoch model for African and European populations
    Population: number_samples (sampling_time_generations):
        AFR: 50 (0)
        EUR: 50 (0)
Contig Description:
    Contig length: 1348131.0
    Mean recombination rate: 8.4e-09
    Mean mutation rate: 5.49e-09
    Genetic map: None

// Initial random seed:
4764614765354

// RunInitializeCallbacks():
initializeTreeSeq();
initializeMutationRate(0);
initializeMutationType(1, 0.5, "f", 0);
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 1348130);
initializeRecombinationRate(8.39993e-06, 1348130);

// Starting run at generation <start>:
1

1: sim.addSubpop(0, 1720);
1: Starting burn-in...
17201: {dbg(self.source); p0.setSubpopulationSize(8603);}
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 11, in <module>
    load_entry_point('stdpopsim', 'console_scripts', 'stdpopsim')()
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 616, in stdpopsim_main
    run(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 607, in run
    args.runner(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 431, in run_simulation
    ts = engine.simulate(**kwargs)
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 636, in simulate
    subprocess.check_call(slim_cmd, stdout=stdout)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['slim', '/tmp/tmpz73arptl.slim']' died with <Signals.SIGKILL: 9>.

real    9m10,979s
user    8m14,345s
sys     0m53,537s
```

With `--slim-scaling-factor 10000`, we generate invalid code (looks like the population size has been scaled down to zero).
```
$ time stdpopsim -e slim -vv --slim-scaling-factor 10000 DroMel -d OutOfAfrica_
2L06 -c chr4 50 50 -o /tmp/DroMel_OutOfAfrica_2L06.trees
2020-04-01 14:49:31,403 [321568] DEBUG stdpopsim.species: Making flat chromosome 1 * chr4
2020-04-01 14:49:31,404 [321568] INFO stdpopsim.cli: Running simulation model OutOfAfrica_2L06 for DroMel on Contig(length=1.3E+06, recombination_rate=8.4E-09, mutation_rate=5.5E-09, genetic_map=None) with 100 samples using slim.
Simulation information:
    Engine: slim (3.3.2)
    Model id: OutOfAfrica_2L06
    Model desciption: Three epoch model for African and European populations
    Population: number_samples (sampling_time_generations):
        AFR: 50 (0)
        EUR: 50 (0)
Contig Description:
    Contig length: 1348131.0
    Mean recombination rate: 8.4e-09
    Mean mutation rate: 5.49e-09
    Genetic map: None

// Initial random seed:
4801515371425

// RunInitializeCallbacks():
initializeTreeSeq();
initializeMutationRate(0);
initializeMutationType(1, 0.5, "f", 0);
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 1348130);
initializeRecombinationRate(8.39929e-05, 1348130);

// Starting run at generation <start>:
1

1: sim.addSubpop(0, 172);
1: Starting burn-in...
1721: {dbg(self.source); p0.setSubpopulationSize(860);}
1765: {dbg(self.source); sim.addSubpopSplit(1,0,0);}
ERROR (Population::AddSubpopulationSplit): subpopulation p1 empty.

Error on script line 1, character 23 (inside runtime script block):

{dbg(self.source); sim.addSubpopSplit(1,0,0);}
                       ^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 11, in <module>
    load_entry_point('stdpopsim', 'console_scripts', 'stdpopsim')()
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 616, in stdpopsim_main
    run(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 607, in run
    args.runner(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 431, in run_simulation
    ts = engine.simulate(**kwargs)
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 636, in simulate
    subprocess.check_call(slim_cmd, stdout=stdout)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['slim', '/tmp/tmpri2hki7p.slim']' returned non-zero exit status 1.

real    1m33,807s
user    1m28,601s
sys     0m4,971s
```

**Comment by petrelharp** [comment]
If we just did a sanity check on the population sizes would that fix this problem? I'd say we should probably throw a warning if any pop sizes are smaller than 100, and an error if smaller than, say, 2? or, 10?

**Comment by grahamgower** [comment]
> If we just did a sanity check on the population sizes would that fix this problem? I'd say we should probably throw a warning if any pop sizes are smaller than 100, and an error if smaller than, say, 2? or, 10?

I've added warnings and errors with #478. The warning applies to fewer than 50 diploid individuals, and an error is raised if the population size will become zero. Similarly, a sample size cannot be requested that is larger than the population size at the time of sampling.

@petrelharp, do you think there's anything to be done about memory consumption? I guess tuning the `simplificationInterval` is best left to SLiM itself? I'm happy to leave this stuff alone, and chalk it up to being "the nature of the beast" for doing forward simulations.

**Comment by petrelharp** [comment]
> @petrelharp, do you think there's anything to be done about memory consumption? I guess tuning the simplificationInterval is best left to SLiM itself?

Yes, but not here. It's possible that a different simplificationInterval scheme would be better, but I don't know what it is, and if anyone does figure it out then we should get it into SLiM itself.  (The biggest thing I'm aware of to decrease memory consumption involves changing the tree sequence recording code so it doesn't have to sort the tables and thus make a copy of them, but that'll be a bit of work.)

**Comment by grahamgower** [comment]
Ok, thanks @petrelharp. I'm happy that any simplificationInterval changes are outside the scope of stdpopsim. #478 has been merged, so I'm going to close this.
