### ISSUE TITLE
error running AncientEurasia_9K19 with Q=100

### ISSUE THREAD

**Issue by jradrion** [popsim-consortium/stdpopsim#463]
just trying to wrap my head around the behaviour of the  `slim-scaling-factor`; when I run the following command:

`stdpopsim -e slim --slim-scaling-factor 100 HomSap -c chr22 -g HapMapII_GRCh37 -d AncientEurasia_9K19 12 12 12 12 12 12 12 12`

I get the following error:

```
ERROR (EidosSymbolTable::_GetValue): undefined identifier p7.

Error on script line 1, character 24 (inside runtime script block):

{dbg(self.source); inds=p7.sampleIndividuals(6); sim.treeSeqRememberIndividuals(inds);}
                        ^^
Traceback (most recent call last):
  File "/home/jadrion/miniconda3/envs/popsim/bin/stdpopsim", line 11, in <module>
    load_entry_point('stdpopsim==0.1.2.dev72+g59af5ea', 'console_scripts', 'stdpopsim')()
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/site-packages/stdpopsim-0.1.2.dev72+g59af5ea-py3.8.egg/stdpopsim/cli.py", line 616, in stdpopsim_main
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/site-packages/stdpopsim-0.1.2.dev72+g59af5ea-py3.8.egg/stdpopsim/cli.py", line 607, in run
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/site-packages/stdpopsim-0.1.2.dev72+g59af5ea-py3.8.egg/stdpopsim/cli.py", line 431, in run_simulation
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/site-packages/stdpopsim-0.1.2.dev72+g59af5ea-py3.8.egg/stdpopsim/slim_engine.py", line 636, in simulate
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['slim', '/tmp/tmp316l7l4d.slim']' returned non-zero exit status 1.
```
I'm assuming that this due to the `slim-scaling-factor` being too high, and not necessarily that it is simply greater than the number of samples (i.e. the above example runs without error with Q=50 but errors out with Q=90)? If so, could someone provide intuition for why this is?

**Comment by grahamgower** [comment]
If you run it with `-vv`, you'll get a listing of the slim callbacks as they happen.

```
$ stdpopsim -vv -e slim --slim-scaling-factor 100 HomSap -c chr22 -g HapMapII_GRCh37 -d AncientEurasia_9K19 12 12 12 12 12 12 12 12 -o /dev/null -q 
2020-04-03 19:49:16,164 [930277] DEBUG stdpopsim.species: Getting map for chr22 from HapMapII_GRCh37
2020-04-03 19:49:16,202 [930277] INFO stdpopsim.cli: Running simulation model AncientEurasia_9K19 for HomSap on Contig(length=5.1E+07, recombination_rate=1.4E-08, mutation_rate=1.3E-08, genetic_map=HapMapII_GRCh37) with 96 samples using slim.
// Initial random seed:
10888726156424

// RunInitializeCallbacks():
initializeTreeSeq();
initializeMutationRate(0);
initializeMutationType(1, 0.5, "f", 0);
initializeGenomicElementType(1, m1, 1);
initializeGenomicElement(g1, 0, 51229804);
initializeRecombinationRate(c(0, 8.09693e-06, 8.13145e-06, 8.1319e-06, 8.13256e-06, 8.12954e-06, 8.02471e-06, 8.02686e-06, 5.68312e-06, 5.68593e-06, 5.68959e-06, 4.4194e-06, 4.41834e-06, 4.42035e-06, 4.31058e-06, 4.29859e-06, 4.29928e-06, 4.29907e-06, 4.31144e-06, 4.32472e-06, 4.32825e-06, 4.32802e-06, 4.328e-06, 4.33314e-06, 4.34765e-06, 4.39322e-06, 4.3967e-06, 4.3967e-06, 4.40609e-06, 4.40641e-06, 4.41025e-06, 3.66608e-06, 4.40666e-06, 4.41358e-06, 4.41369e-06, 4.41317e-06, 4.41381e-06, 4.41343e-06, 4.32376e-06, 4.23465e-06, 4.15943e-06, 3.61128e-06, 2.74719e-06, 2.58494e-06, 1.67211e-06, 1.6637e-06, 1.11387e-07, 1.11391e-07, 1.13358e-07, 1.23635e-07, ...), c(16051346, 16052617, 16053623, 16053658, 16053757, 16054712, 16054959, 16055069, 16055170, 16055206, 16059733, 16061015, 16061341, 16069373, 16072291, 16076926, 16079492, 16099436, 16100058, 16102324, 16103901, 16110035, 16112335, 16136813, 16140627, 16173178, 16201032, 16227430, 16231422, 16252599, 16267520, 16299535, 16317415, 16343552, 16343810, 16344413, 16344571, 16345581, 16346070, 16347193, 16351378, 16351603, 16351851, 16352356, 16364824, 16407119, 16473584, 16477442, 16489238, 16494094, ...));

// Starting run at generation <start>:
1 

1: sim.addSubpop(3, 182);
1: Starting burn-in...
1821: {dbg(self.source); sim.addSubpopSplit(7,182,3);}
1821: {dbg(self.source); p3.setSubpopulationSize(291);}
1821: {dbg(self.source); p7.setSubpopulationSize(182);}
2061: {dbg(self.source); sim.addSubpopSplit(0,173,3);}
2061: {dbg(self.source); p0.setSubpopulationSize(173);}
2061: {dbg(self.source); p3.setSubpopulationSize(23);}
2061: {dbg(self.source); p7.setSubpopulationSize(165);}
2062: {dbg(self.source); gx=sim.generation-2061; size=asInteger(round(165*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2063: {dbg(self.source); gx=sim.generation-2061; size=asInteger(round(165*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2064: {dbg(self.source); gx=sim.generation-2061; size=asInteger(round(165*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2065: {dbg(self.source); gx=sim.generation-2061; size=asInteger(round(165*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2066: {dbg(self.source); gx=sim.generation-2061; size=asInteger(round(165*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2067: {dbg(self.source); sim.addSubpopSplit(8,19,3);}
2067: {dbg(self.source); p7.setSubpopulationSize(28);}
2067: {dbg(self.source); p8.setSubpopulationSize(19);}
2068: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2069: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2070: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2071: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2072: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2073: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
2074: {dbg(self.source); gx=sim.generation-2067; size=asInteger(round(28*exp(-0.291726*gx))); p7.setSubpopulationSize(size);}
```

Looks like population `p7` got too small. SLiM removes populations when they have zero size, hence the error.

**Comment by jradrion** [comment]
Ahh, I see. Once again, thanks @grahamgower!
