### ISSUE TITLE
env broken

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#467]
Looks like maybe the environment is broken. Need to investigate. 

I get an error when trying to use Slim
```
stdpopsim -e slim HomSap -c chr22 -l 0.05 -o foo.ts -d OutOfAfrica_2T12 2 4
```

This is true for me both locally with pip install and in the binder, which uses the environment.yml

**Comment by grahamgower** [comment]
Just when you use the slim engine? Can you post the error message you're getting?

The environment.yml file doesn't mention slim nor pyslim. Maybe these need to be added?

**Comment by agladstein** [comment]
This is the error from Binder, which uses environment.yml.
```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/stdpopsim", line 11, in <module>
    load_entry_point('stdpopsim', 'console_scripts', 'stdpopsim')()
  File "/home/jovyan/src/stdpopsim-master/stdpopsim/cli.py", line 616, in stdpopsim_main
    run(args)
  File "/home/jovyan/src/stdpopsim-master/stdpopsim/cli.py", line 607, in run
    args.runner(args)
  File "/home/jovyan/src/stdpopsim-master/stdpopsim/cli.py", line 429, in run_simulation
    samples=samples, seed=args.seed)
  File "/home/jovyan/src/stdpopsim-master/stdpopsim/cli.py", line 450, in write_simulation_summary
    dry_run_text += f"{indent}Engine: {engine.id} ({engine.get_version()})\n"
  File "/home/jovyan/src/stdpopsim-master/stdpopsim/slim_engine.py", line 548, in get_version
    s = subprocess.check_output([self.slim_path(), "-v"])
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'slim': 'slim'
```

> The environment.yml file doesn't mention slim nor pyslim. Maybe these need to be added?

Yes, I would think so.

When I install with dev instructions, looks like slim is an option, but it still doesn't work:
```
(stdpopsim_env) (base) AriellasNewMBP:stdpopsim agladsteinNew$ python -m stdpopsim
usage: __main__.py [-h] [-V] [-v] [-c CACHE_DIR] [-e {msprime,slim}]
                   [--msprime-model {hudson,dtwf,smc,smc_prime}]
                   [--msprime-change-model T MODEL] [--slim-path PATH]
                   [--slim-script] [--slim-scaling-factor Q]
                   [--slim-burn-in X]
                   {HomSap,AraTha,EscCol,DroMel,CanFam,download-genetic-maps}
                   ...
__main__.py: error: the following arguments are required: subcommand
(stdpopsim_env) (base) AriellasNewMBP:stdpopsim agladsteinNew$ python -m stdpopsim -e slim HomSap -c chr22 -l 0.05 -o foo.ts -d OutOfAfrica_2T12 2 4
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/__main__.py", line 4, in <module>
    cli.stdpopsim_main()
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/cli.py", line 616, in stdpopsim_main
    run(args)
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/cli.py", line 607, in run
    args.runner(args)
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/cli.py", line 429, in run_simulation
    samples=samples, seed=args.seed)
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/cli.py", line 450, in write_simulation_summary
    dry_run_text += f"{indent}Engine: {engine.id} ({engine.get_version()})\n"
  File "/Users/agladsteinNew/dev/stdpopsim/stdpopsim/slim_engine.py", line 559, in get_version
    s = subprocess.check_output([self.slim_path(), "-v"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'slim': 'slim'
```

What is appveyor.yml? because, pslim is mentioned in there, but not in any of the requirements files in requirements directory.

**Comment by jeromekelleher** [comment]
Appveyor.yml is the config file for our Windows CI testing. The environment is complicated because SLiM doesn't work on windows, so we have to make exceptions for it on the different platforms (annoyingly).

Probably the simplest thing is to add ``slim`` to the environment.yml file? Note pyslim isn't available on conda yet either and needs to be installed with pip.

**Comment by agladstein** [comment]
Can someone add this to the installation section of the docs?

**Comment by jeromekelleher** [comment]
Any updates on this @agladstein? Do we need to fix up our environments somewhere?

**Comment by agladstein** [comment]
I'll check this on a clean vm.
