### ISSUE TITLE
PonAbe: genetic maps NaterPP_PonAbe2 and NaterPA_PonAbe2 can't be loaded

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#595]
**Short description of the problem:**
The two orangutan genetic maps are not compatible with msprime's `read_hapmap()` funtion, because the final rate in each file is non-zero.

**How to reproduce the problem:**
```
$ stdpopsim PonAbe -g NaterPP_PonAbe2 10 -o /dev/null
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 33, in <module>
    sys.exit(load_entry_point('stdpopsim', 'console_scripts', 'stdpopsim')())
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 663, in stdpopsim_main
    run(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 654, in run
    args.runner(args)
  File "/home/grg/src/stdpopsim/stdpopsim/cli.py", line 442, in run_simulation
    contig = species.get_contig(
  File "/home/grg/src/stdpopsim/stdpopsim/species.py", line 163, in get_contig
    recomb_map = gm.get_chromosome_map(chrom.id)
  File "/home/grg/src/stdpopsim/stdpopsim/genetic_maps.py", line 152, in get_chromosome_map
    ret = msprime.RecombinationMap.read_hapmap(map_file)
  File "/home/grg/.local/lib/python3.8/site-packages/msprime/simulations.py", line 849, in read_hapmap
    raise ValueError(
ValueError: The last rate provided in the recombination map must zero
```

**Suggested fixes:**
Append a new line to each genetic map file which consists of the chromosome length and rate=0.

**Comment by jeromekelleher** [comment]
Ugh. Agreed on the fix. We really should be unittesting this stuff, but I guess we're not because itwould take to long to run the sims.

What if we ran the sims with an ``end_time=0``? This should at least check that msprime is happy with the inputs and that it will start running.
