### ISSUE TITLE
List available DemographicModels when non-existent one accessed

### ISSUE THREAD

**Issue by hyanwong** [popsim-consortium/stdpopsim#753]
If I do: `model = stdpopsim.get_species("HomSap").get_demographic_model("OOA")`, I currently get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yan/opt/miniconda3/lib/python3.8/site-packages/stdpopsim/species.py", line 295, in get_demographic_model
    raise ValueError(f"DemographicModel '{self.id}/{id}' not in catalog")
ValueError: DemographicModel 'HomSap/OOA' not in catalog
```

It would be nice to (a) list the available models for this species in the raised error, or even, in addition (b) suggest possible "did you mean" options, perhaps simply on the basis of `[models.startswith(id) for models in catalog]` or `['id' in models for models in catalog]`

**Comment by jeromekelleher** [comment]
Probably better to put in a URL to the catalog in the message. The error message would be a wall of text, and hide the traceback context.

**Comment by hyanwong** [comment]
Are there that many possibilities? I just want to know what strings I can bung in there? I don't care about the details of each.

**Comment by hyanwong** [comment]
(NB - a bit like a poor man's autocomplete)

**Comment by grahamgower** [comment]
The catalog is expected to grow, so I agree with @jeromekelleher that having a list of the possibilities is not so desirable moving forward. That said though, it would be nice to have a simple way of printing this list from the command line. At the moment, we just have `--help-models` which also includes the long_description for each model.

**Comment by hyanwong** [comment]
OK, so in the error message if would say how to get this list via the command-line, right? An extra step, but not as tedious as following a URL then trying to grok the page.

**Comment by jeromekelleher** [comment]
Agreed it's good to have ways to access this info from the command line, but exception messages isn't the way to do it.

**Comment by hyanwong** [comment]
If so I'm left with my original complaint. I type some python code into the console, some error comes up saying the test string that I typed isn't valid for some reason (e.g. I didn't capitalise the model name correctly, or got the publication date wrong, or something), and I have no way of finding out what I *should* have typed, other than by traipsing off to some web page to look stuff up (and perhaps I haven't even looked at the web page much before, so it will take me 5 mins to work out what the model strings correspond to). Seems a bit user-unfriendly to me? It definitely interrupted my workflow just now, which is why I brought the issue up. Generally with libraries, I very much appreciate it when the error message gives me pointer on what I should do to get my python command working, rather than just telling me that I've done something wrong? I can't be unusual here?

**Comment by jeromekelleher** [comment]
We could investigate some sort of tab completion in [ipython](https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion) or something? It's not obvious how to do string completion though. I guess we could have a globel models[] object which we could key-complete.

A "did you mean" feature would be neat all right though. Anything in the standard library that'll do that?

**Comment by grahamgower** [comment]
> We could investigate some sort of tab completion in [ipython](https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion) or something? It's not obvious how to do string completion though. I guess we could have a globel models[] object which we could key-complete.

I suppose we could add an Enum? I'm not sure where we'd put it, but I suspect it could easily be autogenerated.

**Comment by hyanwong** [comment]
> A "did you mean" in the message would be neat all right though. Anything in the standard library that'll do that?

How about [difflib.get_close_matches](https://docs.python.org/3/library/difflib.html#difflib.get_close_matches)?

**Comment by jeromekelleher** [comment]
Yes, that looks perfect. A "did you mean" message based on this would be very nice.
