### ISSUE TITLE
The --bibtex-file option seems prone to failure

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#756]
**Short description of the problem:**

It could just be some transient problem, but asking for the citations as a bibtex file is failing for me more often than not (3 failures in 5 attempts).

```
$ stdpopsim HomSap --dry-run --bibtex-file /tmp/foo.bib 10
Simulation information:
    Engine: msprime (1.0.0a4)
    Model id: PiecewiseConstant
    Model desciption: Piecewise constant size population model over multiple epochs.
    Population: number_samples (sampling_time_generations):
        pop0: 10 (0)
Contig Description:
    Contig length: 249250621.0
    Mean recombination rate: 1.1485597641285933e-08
    Mean mutation rate: 1.29e-08
    Genetic map: None

If you use this simulation in published work, please cite:
[stdpopsim]
Adrion et al., 2019: https://doi.org/10.1101/2019.12.20.885129
[simulation engine]
Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
The Genome Sequencing Consortium, 2001: http://dx.doi.org/10.1038/35057062
[mutation rate]
Tian, Browning, and Browning, 2019: https://doi.org/10.1016/j.ajhg.2019.09.012
[recombination rate]
The International HapMap Consortium, 2007: https://doi.org/10.1038/nature06258
[population size]
Takahata, 1993: https://doi.org/10.1093/oxfordjournals.molbev.a039995
[generation time]
Tremblay and Vezina, 2000: https://doi.org/10.1086/302770
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 8, in <module>
    sys.exit(stdpopsim_main())
  File "/home/grg/.local/lib/python3.9/site-packages/stdpopsim/cli.py", line 651, in stdpopsim_main
    run(args)
  File "/home/grg/.local/lib/python3.9/site-packages/stdpopsim/cli.py", line 642, in run
    args.runner(args)
  File "/home/grg/.local/lib/python3.9/site-packages/stdpopsim/cli.py", line 466, in run_simulation
    write_bibtex(engine, model, contig, species, args.bibtex_file)
  File "/home/grg/.local/lib/python3.9/site-packages/stdpopsim/cli.py", line 284, in write_bibtex
    bibtex_file.write(citation.fetch_bibtex())
  File "/home/grg/.local/lib/python3.9/site-packages/stdpopsim/citations.py", line 77, in fetch_bibtex
    with urllib.request.urlopen(req) as con:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout
```

**How to reproduce the problem:**

Ask for bibtex output with `--bibtex-file`. E.g.
```
$ stdpopsim HomSap --dry-run --bibtex-file /tmp/foo.bib 10
```

**Comment by jeromekelleher** [comment]
Hmm. Not sure there's much we can do about that, unless we can find a less overloaded bibtex service?

**Comment by grahamgower** [comment]
Yeah, I dunno either. I'll try again a few times through the week and see if the problem resolves itself.

**Comment by grahamgower** [comment]
I've now tried this on different days and at different times of day. It ranges from slow to "Connection timed out". If there's an alternative service we could use, we should definitely change over.
